class ChangeBuildingTable < ActiveRecord::Migration
  def change
    change_table :buildings do |t|

      t.string  :tax_block
      t.string  :tax_lot
      t.string  :community_district
      t.string  :census_block
      t.string  :school_district
      t.string  :city_council_district
      t.string  :fire_company
      t.string  :police_precinct
      t.string  :zoning_district1
      t.string  :zoning_district2
      t.string  :zoning_district3
      t.string  :zoning_district4
      t.string  :zoning_commercial_overlay1
      t.string  :zoning_commercial_overlay2
      t.string  :zoning_special_purpose_district1
      t.string  :zoning_special_purpose_district2
      t.string  :zoning_limited_height_district
      t.string  :zoning_all_components1
      t.string  :zoning_all_components2
      t.string  :split_zone
      t.string  :building_class
      t.string  :land_use
      t.string  :num_of_easements
      t.string  :type_of_ownership
      t.string  :owner_name
      t.string  :lot_area
      t.string  :floor_area_total
      t.string  :floor_area_commercial
      t.string  :floor_area_residential
      t.string  :floor_area_office
      t.string  :floor_area_retail
      t.string  :floor_area_garage
      t.string  :floor_area_storage
      t.string  :floor_area_factory
      t.string  :floor_area_other
      t.string  :floor_area_area_souce
      t.string  :num_of_buildings
      t.string  :num_of_floors
      t.string  :num_of_residential_units
      t.string  :num_of_total_units
      t.string  :lot_frontage
      t.string  :lot_depth
      t.string  :building_frontage
      t.string  :building_depth
      t.string  :extension_code
      t.string  :proximity_code
      t.string  :irregular_lot_code
      t.string  :lot_type
      t.string  :basement_type_grade
      t.string  :assessed_land_value
      t.string  :assed_total_value
      t.string  :exempt_land_value
      t.string  :exempt_total_value
      t.string  :year_built
      t.string  :year_built_code
      t.string  :year_altered1
      t.string  :year_altered2
      t.string  :historic_district_name
      t.string  :landmark_name
      t.string  :built_floor_area_ratio
      t.string  :maximum_allowable_residential_far
      t.string  :maximum_allowable_commerical_far
      t.string  :maximum_allowable_facility_far
      t.string  :borough_code
      t.string  :borough_tax_block_lot
      t.string  :condominium_number
      t.string  :census_tract2
      t.string  :x_coordinate
      t.string  :y_coordinate
      t.string  :zoning_map_num
      t.string  :zoning_map_code
      t.string  :sanborn_map
      t.string  :tax_map
      t.string  :e_designation_num
      t.string  :apportionment_bbl
      t.string  :appotionment_date
      t.string  :pluto_map_id
      t.string  :version_num
    end
  end
end
